#name: API RAU Health Check


on:
  schedule:
   # - cron: '*/10 * * * *'  # Каждые 10 минут
  workflow_dispatch:  # Ручной запуск


#jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Check API endpoint
        id: api-check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.API_URL_REGIONS }}")
          echo "status_code=$response" >> $GITHUB_OUTPUT
          
          # Отправляем уведомление ТОЛЬКО если статус 200
          if [ "$response" -eq 200 ]; then
            echo "API returned 200 — sending notification"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.TG_CHAT_ID }}" \
              -d text="✅ API Check OK!\nURL: ${{ secrets.API_URL_REGIONS }}\nStatus Code: $response\nTimestamp: $(date --utc +'%Y-%m-%d %H:%M:%S UTC')"
          else
            echo "API returned $response — no notification sent"
          fi
