name: Simple check

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Google
        run: |
          echo "🟢 Начинаю проверку в $(date)"
          
          # Проверяем Google (всегда работает)
          curl -I https://www.google.com --max-time 10
          
          echo "🟢 Проверка завершена"