name: RAU check

on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check URL
        id: check
        run: |
          URL="https://rau.nalog.gov.ru/backend/api/v1/reference-book/regions"
          
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$URL")
          echo "code=$HTTP_CODE" >> $GITHUB_OUTPUT
      
      - name: Send notification on SUCCESS
        if: steps.check.outputs.code == '200'
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          MESSAGE="✅ *Успех!* Код 200"
          curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            -d text="${MESSAGE}"
      
      - name: Send notification on FAILURE
        if: steps.check.outputs.code != '200'
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          MESSAGE="❌ *Ошибка!* Код: ${{ steps.check.outputs.code }}"
          curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            -d text="${MESSAGE}"